sudo: false

language: go

go:
  - 1.10.x
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/stretchr/testify
  - go get github.com/GoASTScanner/gas/cmd/gas/...
  - dep ensure

script:
  - test -z "$(gofmt -s -l -w $(find . -type f -name '*.go' -not -path './vendor/*') | tee /dev/stderr)"
  - test -z "$(golint . |  tee /dev/stderr)"
  - go vet .
  - gas ./...
  - go build -v .
  - go test -v .
